# Generated by Django 3.0.5 on 2020-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Course is Already Exists'}, max_length=30, unique=True)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='admintable',
            name='contact_no',
            field=models.IntegerField(error_messages={'unique': 'Phone Number is Already Exists'}, unique=True),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email ID is Already Exists'}, max_length=254, unique=True),
        ),
    ]
