# Generated by Django 3.0.5 on 2020-07-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20200714_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleclassesTable',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.CourseTable')),
            ],
        ),
    ]
