# Generated by Django 3.0.5 on 2020-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_remove_scheduleclassestable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleclassestable',
            name='date',
            field=models.DateField(),
        ),
    ]
