# Generated by Django 3.0.5 on 2020-07-14 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200715_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleclassestable',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
    ]
